### ISSUE TITLE
Error loading a non-existing nc file

### ISSUE THREAD

**Issue by patel-zeel** [AleksandarSekulic/MeteoSerbia1km#1]
I am getting an error while executing this line of code in 4_final_script.R
```R
eobs <- foreach(date = dates, .packages = c("raster","spacetime","gstat","rgdal","raster","doParallel","meteo")) %dopar% {
# for (date in dates) {
  # day<-gsub("-","",date,fixed=TRUE)
  band = as.integer(date - as.Date("1950-01-01")) + 1
  r <- raster(paste("eobs/", var, "_ens_mean_0.1deg_reg_v21.0e.nc", sep=""), band=band)
  # r@z[[1]]
  # get ogimet_serbia date
  ogimet_day <- ogimet_serbia[ogimet_serbia$date==date, ]
  coordinates(ogimet_day) <-~ lon+lat
  return(raster::extract(r, ogimet_day))
}
```
Output
```
Error in { : 
  task 1 failed - "Error in nc_open trying to open file eobs/tmax_ens_mean_0.1deg_reg_v21.0e.nc"
```

**Comment by AleksandarSekulic** [comment]
Hi.
You have to download eobs data first. You can download it from [here](https://surfobs.climate.copernicus.eu/dataaccess/access_eobs.php) and place it under the eobs/ folder. I named the .nc files as {var}_ens_mean_0.1deg_reg_v21.0e.nc".
Great that you notice this, I'll add download of the eobs data in the code.

**Comment by patel-zeel** [comment]
Hi, 
sounds great! Thank you for your quick response and resolution :)
